// Fallback data for when Sanity CMS is not connected or has no content yet.
// This ensures the site renders beautifully on first deploy.

export const fallbackSettings = {
  churchName: 'New Life In God\'s Word — Carmen',
  tagline: 'A Christ-centered discipleship church in Carmen, Davao del Norte dedicated to winning souls and making disciples.',
  serviceTimes: [
    { day: 'Sunday', time: '8:00 AM', label: 'Sunday Worship Celebration' },
    { day: 'Wednesday', time: '6:30 PM', label: 'Midweek Service' },
  ],
  address: 'Purok 14, Ising, Carmen, Davao del Norte, Philippines',
  facebookUrl: 'https://www.facebook.com/NLIGW.OFFICIALS',
  gcashNumber: '0917-XXX-XXXX',
  mayaNumber: '0917-XXX-XXXX',
  bankName: 'BDO',
  bankAccountName: 'New Life In God\'s Word Carmen',
  bankAccountNumber: 'XXXX-XXXX-XXXX',
  contactNumbers: [
    { label: 'Church Office', number: '0917-XXX-XXXX' },
    { label: 'Pastor', number: '0918-XXX-XXXX' },
  ],
}

export const fallbackSermons = [
  {
    _id: 'sermon-1',
    title: 'Walking in Faith',
    speaker: 'Pastor James',
    series: 'Foundations of Faith',
    date: '2026-08-24',
    videoUrl: '',
    coverImage: null,
    scriptureReferences: ['Hebrews 11:1', 'Romans 10:17'],
  },
  {
    _id: 'sermon-2',
    title: 'The Power of Prayer',
    speaker: 'Pastor James',
    series: 'Foundations of Faith',
    date: '2026-08-17',
    videoUrl: '',
    coverImage: null,
    scriptureReferences: ['Philippians 4:6-7', 'Matthew 7:7'],
  },
  {
    _id: 'sermon-3',
    title: 'Living with Purpose',
    speaker: 'Guest Speaker',
    series: 'Purpose Driven',
    date: '2026-08-10',
    videoUrl: '',
    coverImage: null,
    scriptureReferences: ['Jeremiah 29:11', 'Ephesians 2:10'],
  },
  {
    _id: 'sermon-4',
    title: 'Hope in Difficult Times',
    speaker: 'Pastor James',
    series: 'Unshakeable Hope',
    date: '2026-08-03',
    videoUrl: '',
    coverImage: null,
    scriptureReferences: ['Romans 8:28', 'Isaiah 41:10'],
  },
  {
    _id: 'sermon-5',
    title: 'The Heart of Worship',
    speaker: 'Pastor Grace',
    series: 'Worship Redefined',
    date: '2026-07-27',
    videoUrl: '',
    coverImage: null,
    scriptureReferences: ['John 4:24', 'Psalm 95:1-2'],
  },
  {
    _id: 'sermon-6',
    title: 'Community of Believers',
    speaker: 'Pastor James',
    series: 'Stronger Together',
    date: '2026-07-20',
    videoUrl: '',
    coverImage: null,
    scriptureReferences: ['Acts 2:42-47', 'Hebrews 10:25'],
  },
]

export const fallbackEvents = [
  {
    _id: 'event-1',
    title: 'Sunday Worship Celebration',
    date: '2026-09-07T09:00:00Z',
    location: 'NLIGW Carmen Main Hall',
    description: 'Join us for a powerful time of praise, worship, and the Word. Everyone is welcome!',
    registrationLink: '',
    eventPoster: null,
  },
  {
    _id: 'event-2',
    title: 'Youth Fellowship Night',
    date: '2026-09-12T18:00:00Z',
    location: 'NLIGW Carmen Youth Center',
    description: 'A night of fun, games, worship, and God\'s Word for young people ages 13-25.',
    registrationLink: '',
    eventPoster: null,
  },
  {
    _id: 'event-3',
    title: 'Water Baptism Service',
    date: '2026-09-21T14:00:00Z',
    location: 'Carmen Public Beach',
    description: 'Public declaration of faith through water baptism. Contact the church office to sign up.',
    registrationLink: '',
    eventPoster: null,
  },
]

export const fallbackMinistries = [
  {
    _id: 'min-1',
    name: 'Life Groups (Cell Network)',
    category: 'lifegroups',
    leaderName: 'Pastors & Cell Leaders',
    meetingSchedule: 'Weekly in homes across Carmen',
    description: 'The heartbeat of our church. Weekly small group gatherings where we grow in fellowship, care for one another, study God\'s Word, and win souls for Christ.',
    heroImage: null,
  },
  {
    _id: 'min-2',
    name: 'School of Leaders (SOL)',
    category: 'lifegroups',
    leaderName: 'Leadership Academy',
    meetingSchedule: 'Modular Discipleship Classes',
    description: 'Equipping every believer through biblical doctrine, character development, and practical leadership skills to lead and mentor others.',
    heroImage: null,
  },
  {
    _id: 'min-3',
    name: 'NLIGW Youth Generation',
    category: 'youth',
    leaderName: 'Brother Mark Reyes',
    meetingSchedule: 'Every Friday, 7:00 PM',
    description: 'A dynamic generation of young leaders passionate for Jesus, leading campus life groups, and reaching the youth of Carmen.',
    heroImage: null,
  },
  {
    _id: 'min-4',
    name: 'Men of Valor (Men\'s Ministry)',
    category: 'men',
    leaderName: 'Brother David',
    meetingSchedule: 'Every 2nd Saturday, 7:00 AM',
    description: 'Raising godly fathers, husbands, and leaders who govern their homes with integrity and lead their cells with spiritual passion.',
    heroImage: null,
  },
  {
    _id: 'min-5',
    name: 'Women of Grace (Women\'s Ministry)',
    category: 'women',
    leaderName: 'Sister Ruth & Pastor Grace',
    meetingSchedule: 'Every 2nd Saturday, 9:00 AM',
    description: 'Empowering women of faith to flourish in discipleship, build strong families, and lead vibrant life groups.',
    heroImage: null,
  },
  {
    _id: 'min-6',
    name: 'Worship & Creative Arts Team',
    category: 'worship',
    leaderName: 'Brother Joshua',
    meetingSchedule: 'Rehearsal: Saturday 4:00 PM',
    description: 'Leading the church into God\'s presence through passionate praise, prophetic worship, and creative ministry.',
    heroImage: null,
  },
]

export const fallbackPastoralTeam = [
  {
    _id: 'pastor-1',
    name: 'Pastor James Santos',
    title: 'Senior Pastor',
    photo: null,
    bio: 'Pastor James has been faithfully leading NLIGW Carmen for over 10 years, committed to teaching God\'s Word and shepherding the flock with love and wisdom.',
  },
  {
    _id: 'pastor-2',
    name: 'Pastor Grace Santos',
    title: 'Co-Pastor / Women\'s Ministry',
    photo: null,
    bio: 'Pastor Grace leads the Women of Grace ministry and is passionate about discipleship, family ministry, and community outreach.',
  },
  {
    _id: 'pastor-3',
    name: 'Brother Mark Reyes',
    title: 'Youth Pastor',
    photo: null,
    bio: 'Brother Mark leads the youth ministry with energy and passion, helping young people discover their God-given purpose.',
  },
]
